import pprint
from typing import Any, Dict


def generate_cadquery_script_from_plan(cad_plan: Dict[str, Any]) -> str:
    """
    Generate a CadQuery Python script from an OMNI Forge CAD parameter plan.

    Level 3 goal:
    Convert structured CAD parameters into a real script that can later be
    executed to create STEP/STL files.

    This function only returns script text.
    It does not execute CadQuery.
    """

    part_type = cad_plan.get("part_type", "unknown")

    if part_type == "camera_mount":
        return _generate_camera_mount_script(cad_plan)

    return _generate_generic_part_script(cad_plan)


def _generate_camera_mount_script(cad_plan: Dict[str, Any]) -> str:
    parameters = cad_plan.get("parameters", {})
    param_block = pprint.pformat(parameters, indent=4, sort_dicts=True)

    return f'''"""
Generated by OMNI Forge.

Part type:
    camera_mount

Purpose:
    Prototype CAD script for a printable Raspberry Pi camera mount.

Safety:
    This script only generates geometry.
    Do not start physical printing without human approval and printer safety checks.

Requirements:
    pip install cadquery

Outputs:
    exports/camera_mount.step
    exports/camera_mount.stl
"""

from pathlib import Path

try:
    import cadquery as cq
except ImportError as error:
    raise SystemExit(
        "CadQuery is required to run this generated script. "
        "Install later with: pip install cadquery"
    ) from error


PARAMETERS = {param_block}


def build_model():
    p = PARAMETERS

    base_width = p.get("base_plate_width_mm", 60)
    base_depth = p.get("base_plate_depth_mm", 42)
    base_thickness = p.get("base_plate_thickness_mm", 4)

    wall_height = p.get("mount_wall_height_mm", 38)
    wall_thickness = p.get("mount_wall_thickness_mm", 5)
    mount_angle = p.get("mount_angle_degrees", 25)

    hole_diameter = p.get("screw_hole_diameter_mm", 3.2)
    hole_spacing = p.get("screw_hole_spacing_mm", 45)
    fillet_radius = p.get("fillet_radius_mm", 3)

    cable_width = p.get("cable_channel_width_mm", 10)
    cable_height = p.get("cable_channel_height_mm", 5)

    # -----------------------------------------------------
    # Base plate
    # -----------------------------------------------------
    base = (
        cq.Workplane("XY")
        .box(base_width, base_depth, base_thickness)
    )

    if fillet_radius > 0:
        base = base.edges("|Z").fillet(fillet_radius)

    # Screw holes through the base plate.
    screw_points = [
        (-hole_spacing / 2, 0),
        (hole_spacing / 2, 0),
    ]

    base = (
        base.faces(">Z")
        .workplane()
        .pushPoints(screw_points)
        .hole(hole_diameter)
    )

    # -----------------------------------------------------
    # Angled camera support wall
    # -----------------------------------------------------
    support = (
        cq.Workplane("XY")
        .box(base_width * 0.70, wall_thickness, wall_height)
        .translate((
            0,
            base_depth / 2 - wall_thickness / 2,
            base_thickness / 2 + wall_height / 2,
        ))
    )

    # Rotate around the X-axis to create the intended camera viewing angle.
    support = support.rotate(
        (0, base_depth / 2, base_thickness / 2),
        (1, 0, 0),
        -mount_angle,
    )

    model = base.union(support)

    # -----------------------------------------------------
    # Cable clearance channel
    # -----------------------------------------------------
    cable_cut = (
        cq.Workplane("XY")
        .box(cable_width, base_depth, cable_height)
        .translate((
            0,
            0,
            base_thickness / 2,
        ))
    )

    model = model.cut(cable_cut)

    return model


def export_model(model):
    output_dir = Path(__file__).resolve().parent / "exports"
    output_dir.mkdir(parents=True, exist_ok=True)

    step_path = output_dir / "camera_mount.step"
    stl_path = output_dir / "camera_mount.stl"

    cq.exporters.export(model, str(step_path))
    cq.exporters.export(model, str(stl_path))

    print(f"Exported STEP: {{step_path}}")
    print(f"Exported STL:  {{stl_path}}")


if __name__ == "__main__":
    cad_model = build_model()
    export_model(cad_model)
'''


def _generate_generic_part_script(cad_plan: Dict[str, Any]) -> str:
    parameters = cad_plan.get("parameters", {})
    part_type = cad_plan.get("part_type", "generic_part")
    param_block = pprint.pformat(parameters, indent=4, sort_dicts=True)

    return f'''"""
Generated by OMNI Forge.

Part type:
    {part_type}

Purpose:
    Generic printable workshop part placeholder.

Requirements:
    pip install cadquery
"""

from pathlib import Path

try:
    import cadquery as cq
except ImportError as error:
    raise SystemExit(
        "CadQuery is required to run this generated script. "
        "Install later with: pip install cadquery"
    ) from error


PARAMETERS = {param_block}


def build_model():
    p = PARAMETERS

    length = p.get("default_length_mm", 60)
    width = p.get("default_width_mm", 40)
    thickness = p.get("default_thickness_mm", 4)
    fillet_radius = p.get("fillet_radius_mm", 3)

    model = cq.Workplane("XY").box(length, width, thickness)

    if fillet_radius > 0:
        model = model.edges("|Z").fillet(fillet_radius)

    return model


def export_model(model):
    output_dir = Path(__file__).resolve().parent / "exports"
    output_dir.mkdir(parents=True, exist_ok=True)

    step_path = output_dir / "{part_type}.step"
    stl_path = output_dir / "{part_type}.stl"

    cq.exporters.export(model, str(step_path))
    cq.exporters.export(model, str(stl_path))

    print(f"Exported STEP: {{step_path}}")
    print(f"Exported STL:  {{stl_path}}")


if __name__ == "__main__":
    cad_model = build_model()
    export_model(cad_model)
'''