"""
Generated by OMNI Command.

Package: omni_rover
Node: camera_node
Purpose: Captures images from the camera module.
"""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Image


class CameraNode(Node):
    def __init__(self):
        super().__init__("camera_node")

        self.declare_parameter("unknown", None)

        self.camera_images_publisher = self.create_publisher(Image, "/camera_images", 10)

        # No subscribers configured yet.

        self.create_timer(1.0, self.publish_camera_images)

        self.get_logger().info("camera_node started.")

    def publish_camera_images(self):
        msg = Image()
        self.camera_images_publisher.publish(msg)
        self.get_logger().info("Published Image on /camera_images")


def main(args=None):
    rclpy.init(args=args)

    node = CameraNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
