"""
Generated by OMNI Command.

Package: omni_rover
Node: distance_sensor_node
Purpose: Reads data from the ultrasonic sensor.
"""

import rclpy
from rclpy.node import Node
from std_msgs.msg import String


class DistanceSensorNode(Node):
    def __init__(self):
        super().__init__("distance_sensor_node")

        self.declare_parameter("unknown", None)

        self.distance_data_publisher = self.create_publisher(String, "/distance_data", 10)

        self.navigation_goal_subscription = self.create_subscription(String, "/navigation_goal", self.handle_navigation_goal, 10)

        self.create_timer(1.0, self.publish_distance_data)

        self.get_logger().info("distance_sensor_node started.")

    def publish_distance_data(self):
        msg = String()
        msg.data = "distance_sensor_node heartbeat"
        self.distance_data_publisher.publish(msg)
        self.get_logger().info("Published on /distance_data: " + msg.data)

    def handle_navigation_goal(self, msg):
        self.get_logger().info("Received message on /navigation_goal")


def main(args=None):
    rclpy.init(args=args)

    node = DistanceSensorNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
