"""
Generated by OMNI Command.

Package: omni_rover
Node: imu_node
Purpose: Collects data from the IMU.
"""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Imu


class ImuNode(Node):
    def __init__(self):
        super().__init__("imu_node")

        self.declare_parameter("unknown", None)

        self.imu_data_publisher = self.create_publisher(Imu, "/imu_data", 10)

        # No subscribers configured yet.

        self.create_timer(1.0, self.publish_imu_data)

        self.get_logger().info("imu_node started.")

    def publish_imu_data(self):
        msg = Imu()
        self.imu_data_publisher.publish(msg)
        self.get_logger().info("Published Imu on /imu_data")


def main(args=None):
    rclpy.init(args=args)

    node = ImuNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
