"""
Generated by OMNI Command.

Package: omni_rover
Node: motor_control_node
Purpose: Controls the DC motors for movement.
"""

import rclpy
from rclpy.node import Node
from geometry_msgs.msg import Twist
from std_msgs.msg import String


class MotorControlNode(Node):
    def __init__(self):
        super().__init__("motor_control_node")

        self.declare_parameter("unknown", None)

        self.cmd_vel_publisher = self.create_publisher(Twist, "/cmd_vel", 10)

        self.motor_commands_subscription = self.create_subscription(String, "/motor_commands", self.handle_motor_commands, 10)

        self.create_timer(1.0, self.publish_cmd_vel)

        self.get_logger().info("motor_control_node started.")

    def publish_cmd_vel(self):
        msg = Twist()
        self.cmd_vel_publisher.publish(msg)
        self.get_logger().info("Published Twist on /cmd_vel")

    def handle_motor_commands(self, msg):
        self.get_logger().info("Received message on /motor_commands")


def main(args=None):
    rclpy.init(args=args)

    node = MotorControlNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
