"""
Generated by OMNI Command.

Package: omni_rover
Node: navigation_node
Purpose: Handles navigation logic.
"""

import rclpy
from rclpy.node import Node
from sensor_msgs.msg import Imu
from std_msgs.msg import String


class NavigationNode(Node):
    def __init__(self):
        super().__init__("navigation_node")

        self.declare_parameter("unknown", None)

        self.navigation_goal_publisher = self.create_publisher(String, "/navigation_goal", 10)

        self.distance_data_subscription = self.create_subscription(String, "/distance_data", self.handle_distance_data, 10)
        self.imu_data_subscription = self.create_subscription(Imu, "/imu_data", self.handle_imu_data, 10)

        self.create_timer(1.0, self.publish_navigation_goal)

        self.get_logger().info("navigation_node started.")

    def publish_navigation_goal(self):
        msg = String()
        msg.data = "navigation_node heartbeat"
        self.navigation_goal_publisher.publish(msg)
        self.get_logger().info("Published on /navigation_goal: " + msg.data)

    def handle_distance_data(self, msg):
        self.get_logger().info("Received message on /distance_data")

    def handle_imu_data(self, msg):
        self.get_logger().info("Received message on /imu_data")


def main(args=None):
    rclpy.init(args=args)

    node = NavigationNode()

    try:
        rclpy.spin(node)
    except KeyboardInterrupt:
        pass
    finally:
        node.destroy_node()
        rclpy.shutdown()


if __name__ == "__main__":
    main()
