from __future__ import annotations

import csv
import json
from pathlib import Path
from typing import Any, Dict, List


class KiCadProjectGenerator:
    def __init__(self, output_root: str | Path):
        self.output_root = Path(output_root)

    def generate(self, mission_slug: str, electronics_plan: Dict[str, Any]) -> Dict[str, str]:
        project_dir = self.output_root / mission_slug / "generated_kicad"
        project_dir.mkdir(parents=True, exist_ok=True)

        project_name = mission_slug.replace("-", "_")

        files = {}

        files["README.md"] = self._write_readme(project_dir, project_name, electronics_plan)
        files["electronics_architecture.json"] = self._write_json(
            project_dir,
            "electronics_architecture.json",
            electronics_plan,
        )
        files["power_budget.json"] = self._write_json(
            project_dir,
            "power_budget.json",
            electronics_plan.get("power_budget", {}),
        )
        files["connector_map.json"] = self._write_json(
            project_dir,
            "connector_map.json",
            electronics_plan.get("connector_map", {}),
        )
        files["bom.csv"] = self._write_bom(
            project_dir,
            electronics_plan.get("bom", []),
        )
        files[f"{project_name}.kicad_pro"] = self._write_kicad_project(
            project_dir,
            project_name,
        )
        files[f"{project_name}.kicad_sch"] = self._write_placeholder_schematic(
            project_dir,
            project_name,
        )
        files[f"{project_name}.kicad_pcb"] = self._write_placeholder_pcb(
            project_dir,
            project_name,
        )

        return files

    def _write_json(self, project_dir: Path, filename: str, data: Dict[str, Any]) -> str:
        path = project_dir / filename
        path.write_text(json.dumps(data, indent=2), encoding="utf-8")
        return str(path)

    def _write_readme(self, project_dir: Path, project_name: str, plan: Dict[str, Any]) -> str:
        path = project_dir / "README.md"
        text = f"""# KiCAD Electronics Package — {project_name}

This folder was generated by OMNI.

## Purpose

Generate an initial electronics design package for the mission.

## Included Artifacts

- electronics_architecture.json
- power_budget.json
- connector_map.json
- bom.csv
- {project_name}.kicad_pro
- {project_name}.kicad_sch
- {project_name}.kicad_pcb

## Notes

The KiCAD schematic and PCB are starter placeholders. Review all electrical choices before fabrication.

## Electronics Summary

{plan.get("summary", "No summary provided.")}
"""
        path.write_text(text, encoding="utf-8")
        return str(path)

    def _write_bom(self, project_dir: Path, bom: List[Dict[str, Any]]) -> str:
        path = project_dir / "bom.csv"

        fieldnames = [
            "reference",
            "quantity",
            "component",
            "value",
            "footprint",
            "notes",
        ]

        with path.open("w", newline="", encoding="utf-8") as csvfile:
            writer = csv.DictWriter(csvfile, fieldnames=fieldnames)
            writer.writeheader()

            for row in bom:
                writer.writerow({
                    "reference": row.get("reference", ""),
                    "quantity": row.get("quantity", ""),
                    "component": row.get("component", ""),
                    "value": row.get("value", ""),
                    "footprint": row.get("footprint", ""),
                    "notes": row.get("notes", ""),
                })

        return str(path)

    def _write_kicad_project(self, project_dir: Path, project_name: str) -> str:
        path = project_dir / f"{project_name}.kicad_pro"

        # Minimal KiCAD project JSON.
        # KiCAD may add additional settings after opening/saving.
        content = {
            "board": {
                "design_settings": {
                    "defaults": {},
                    "rules": {}
                }
            },
            "boards": [],
            "cvpcb": {},
            "erc": {},
            "libraries": {},
            "meta": {
                "filename": f"{project_name}.kicad_pro",
                "version": 1
            },
            "net_settings": {},
            "pcbnew": {},
            "schematic": {},
            "sheets": [],
            "text_variables": {}
        }

        path.write_text(json.dumps(content, indent=2), encoding="utf-8")
        return str(path)

    def _write_placeholder_schematic(self, project_dir: Path, project_name: str) -> str:
        path = project_dir / f"{project_name}.kicad_sch"

        content = f"""(kicad_sch
  (version 20230121)
  (generator "OMNI")
  (paper "A4")
  (title_block
    (title "{project_name}")
    (company "OMNI Generated Electronics Package")
    (comment 1 "Placeholder schematic. Review before use.")
  )
)
"""
        path.write_text(content, encoding="utf-8")
        return str(path)

    def _write_placeholder_pcb(self, project_dir: Path, project_name: str) -> str:
        path = project_dir / f"{project_name}.kicad_pcb"

        content = f"""(kicad_pcb
  (version 20240108)
  (generator "OMNI")
  (general)
  (paper "A4")
  (layers
    (0 "F.Cu" signal)
    (31 "B.Cu" signal)
    (32 "B.Adhes" user "B.Adhesive")
    (33 "F.Adhes" user "F.Adhesive")
    (34 "B.Paste" user)
    (35 "F.Paste" user)
    (36 "B.SilkS" user "B.Silkscreen")
    (37 "F.SilkS" user "F.Silkscreen")
    (38 "B.Mask" user)
    (39 "F.Mask" user)
    (44 "Edge.Cuts" user)
  )
  (title_block
    (title "{project_name}")
    (company "OMNI Generated Electronics Package")
    (comment 1 "Placeholder PCB. Review before use.")
  )
)
"""
        path.write_text(content, encoding="utf-8")
        return str(path)